<?php if($block->canShow() && $block->isCurrentProductPriceInRange()):?>

    <div class="creditea-calc-msi">
        <img loading="lazy" src="<?php echo $block->getBrandUrl()?>" alt="creditea"> <span>Desde <?= $block->getPesosQuincenalesFormatted(); ?> pesos quincenales <a href="<?php echo $block->getUrlCreditea(); ?>" data-vbtype="iframe" data-customclass="popup-creditea" class="creditea-click">Ver Más</a></span>
    </div>

    <script nonce="<?= $block->getCspNonce() ?>">require(['jquery', 'creditea-venobox'], function($){$('a.creditea-click').venobox();});</script>

    <style>
        .venoframe.vbox-figlio {height: 90vh;}
        .creditea-calc-msi > img {width: 134px;}
        .creditea-calc-msi > span {padding-top: 5px;}
        .creditea-calc-msi {line-height:30px; padding: 3px 0px;}
        .creditea-calc-msi > * {display:inline-block; vertical-align: middle;}
    </style>
<?php endif; ?>