<?php if($block->canShow(true)):?>
    <?php if ($block->showBannerCart()): ?>
        <a href="javascript:void(0);" data-image="<?=  $block->getBannerUrl('promo_modal_content') ?>" class="creditea-modal-trigger creditea-promo-click">
            <img src="<?= $block->getBannerUrl('cart_below_summary') ?>" alt="Promo Image Under Cart Summary" />
        </a>
        <script nonce="<?= $block->getCspNonce() ?>">require(['jquery', 'creditea-venobox-promo']);</script>
    <?php endif; ?>
<?php endif; ?>